# Generated by Django 3.2.8 on 2021-11-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_items',
            fields=[
                ('deliveryid', models.AutoField(primary_key=True, serialize=False)),
                ('checkoutid', models.CharField(max_length=100)),
                ('productid', models.CharField(max_length=100)),
                ('customerid', models.CharField(max_length=100)),
                ('customer_checkout', models.CharField(max_length=100)),
                ('ordred_date', models.DateTimeField(auto_now_add=True)),
                ('dispached_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
