# Generated by Django 3.2.8 on 2021-11-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_dispatched_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatched_items',
            name='delivery_ststus',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
