# Generated by Django 3.2.8 on 2021-11-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_ustomerid_user_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_city',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address_contry',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address_home',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address_state',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
