# Generated by Django 3.2.8 on 2021-11-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211125_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
