# Generated by Django 3.2.8 on 2021-11-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkoutitem',
            fields=[
                ('checkoutid', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.CharField(max_length=100)),
                ('customerid', models.CharField(max_length=100)),
                ('customer_checkout', models.CharField(max_length=100)),
            ],
        ),
    ]
