# Generated by Django 3.2.8 on 2021-11-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ustomerID',
            new_name='customerID',
        ),
    ]
