# Generated by Django 3.2.8 on 2021-11-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dispatched_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=500)),
                ('customer_phone', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_dis', models.CharField(max_length=500)),
                ('product_price', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='del')),
                ('ordred_date', models.DateTimeField(auto_now_add=True)),
                ('dispached_date', models.DateTimeField()),
            ],
        ),
    ]
