# Generated by Django 3.2.8 on 2021-11-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_dispatched_items_delivery_ststus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatched_items',
            name='dispached_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
