# Generated by Django 3.2.8 on 2021-11-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_dispatched_items_dispached_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_items',
            old_name='customer_checkout',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='delivery_items',
            old_name='dispached_date',
            new_name='deliverd_date',
        ),
        migrations.RenameField(
            model_name='delivery_items',
            old_name='customerid',
            new_name='product_brand',
        ),
        migrations.RenameField(
            model_name='delivery_items',
            old_name='productid',
            new_name='product_name',
        ),
    ]
