# Generated by Django 3.2.8 on 2021-11-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_catogary', models.CharField(max_length=50)),
                ('product_brand', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_dis', models.CharField(max_length=250)),
                ('product_price', models.IntegerField()),
                ('product_offer', models.BooleanField(default=False)),
                ('product_stock', models.IntegerField()),
            ],
        ),
    ]
